language: php

php:
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: SF_4="true"

before_install:
    - phpenv config-rm xdebug.ini

install: composer update $COMPOSER_FLAGS --prefer-stable

script: ./phpunit
